import {describe,expect,it} from 'vitest'
import {buildInstitutionStudentReportSnapshot,institutionStudentReportMutationSchema,institutionStudentReportSnapshotSchema} from '../student-report'

const snapshot={modelVersion:'institution-student-report-v1',generatedAt:'2026-08-14T10:00:00.000Z',periodStart:'2026-08-01T10:00:00.000Z',periodEnd:'2026-08-14T10:00:00.000Z',institutionName:'Bilge Pilot Kursu',classroomName:'TYT A Sınıfı',teacherAlias:'Öğretmen Bir',studentAlias:'Öğrenci Bir',scope:{game:'matematik',examRef:'TYT',taxonomyVersion:'ba-tyt-math-v1'},summary:{outcomeCount:1,assessedOutcomeCount:1,insufficientOutcomeCount:0,developingOutcomeCount:1,masteredOutcomeCount:0},outcomes:[{title:'Temel Kavramlar',path:['TYT Matematik','Sayılar','Temel','Kavram'],status:'developing',score:62,confidence:'medium',evidenceCount:8,independentEvidenceCount:4,lastEvidenceAt:'2026-08-13T10:00:00.000Z'}]}
describe('institution student report snapshot',()=>{
  it('accepts and safely normalizes an internally consistent legacy Math report',()=>{const parsed=institutionStudentReportSnapshotSchema.safeParse(snapshot);expect(parsed.success).toBe(true);if(parsed.success)expect(parsed.data.scope).toMatchObject({questionExamRef:'TYT',scopePolicyVersion:'institution-scope-v1'});expect(JSON.stringify(snapshot)).not.toMatch(/memberRef|studentId|email|phone|note/)})
  it('rejects summary drift and extra identifier fields',()=>{expect(institutionStudentReportSnapshotSchema.safeParse({...snapshot,summary:{...snapshot.summary,outcomeCount:2}}).success).toBe(false);expect(institutionStudentReportSnapshotSchema.safeParse({...snapshot,memberRef:'a'.repeat(32)}).success).toBe(false)})
  it('preserves the analysis taxonomy version in a generated report',()=>{
    const analysis={classroom:{id:'11111111-1111-4111-8111-111111111111',name:'TYT A Sınıfı'},student:{memberRef:'a'.repeat(32),alias:'Öğrenci Bir',joinedAt:'2026-08-01T10:00:00.000Z'},scope:{game:'fen',examRef:'TYT',questionExamRef:'TYT',taxonomyVersion:'ba-tyt-fen-v2',diagnosticEnabled:false,institutionReportingEnabled:true,scopePolicyVersion:'institution-scope-v1',modelVersion:'institution-evidence-v2',windowStart:'2026-08-01T10:00:00.000Z',windowEnd:'2026-08-14T10:00:00.000Z'},coverage:{supported:true,totalQuestions:120,mappedQuestions:120,percentage:100},summary:snapshot.summary,outcomes:[{code:'FEN-01',nodeCode:'ba-tyt-fen-v2:outcome:fen-01',path:['TYT Fen Bilimleri','Fizik','Temel','Kavram'],title:'Temel Kavramlar',category:'fizik',assessment:{outcomeCode:'FEN-01',status:'developing',score:62,confidence:'medium',evidence:{evidenceCount:8,independentEvidenceCount:4,firstEvidenceAt:'2026-08-02T10:00:00.000Z',lastEvidenceAt:'2026-08-13T10:00:00.000Z',windowStart:'2026-08-01T10:00:00.000Z',windowEnd:'2026-08-14T10:00:00.000Z',modelVersion:'institution-evidence-v2',taxonomyVersion:'ba-tyt-fen-v2',coverageSupported:true}},details:{correctEvidenceCount:5,delayedCorrectCount:1,rawAccuracy:62,difficultyAccuracy:62,hintRate:0,fastWrongRate:0,components:{accuracy:62,delayedRetrieval:50,independence:80,selfRegulation:80},diagnosticSources:[]}}]}
    expect(buildInstitutionStudentReportSnapshot(analysis,{institutionName:'Bilge Pilot Kursu',teacherAlias:'Öğretmen Bir'})?.scope).toEqual({game:'fen',examRef:'TYT',questionExamRef:'TYT',taxonomyVersion:'ba-tyt-fen-v2',scopePolicyVersion:'institution-scope-v1'})
  })
  it('rejects a v2 wire result whose envelope and immutable snapshot scopes disagree',()=>{const parsed=institutionStudentReportSnapshotSchema.parse(snapshot);expect(institutionStudentReportMutationSchema.safeParse({reportRef:'b'.repeat(32),scope:{...parsed.scope,game:'fen',taxonomyVersion:'ba-tyt-fen-v1'},snapshot:parsed,createdAt:'2026-08-14T10:01:00.000Z',replayed:false}).success).toBe(false)})
})
