import {describe,expect,it} from 'vitest'
import {buildInstitutionStudentReportSnapshot,institutionStudentReportSnapshotSchema} from '../student-report'

const snapshot={modelVersion:'institution-student-report-v1',generatedAt:'2026-08-14T10:00:00.000Z',periodStart:'2026-08-01T10:00:00.000Z',periodEnd:'2026-08-14T10:00:00.000Z',institutionName:'Bilge Pilot Kursu',classroomName:'TYT A Sınıfı',teacherAlias:'Öğretmen Bir',studentAlias:'Öğrenci Bir',scope:{game:'matematik',examRef:'TYT',taxonomyVersion:'ba-tyt-math-v1'},summary:{outcomeCount:1,assessedOutcomeCount:1,insufficientOutcomeCount:0,developingOutcomeCount:1,masteredOutcomeCount:0},outcomes:[{title:'Temel Kavramlar',path:['TYT Matematik','Sayılar','Temel','Kavram'],status:'developing',score:62,confidence:'medium',evidenceCount:8,independentEvidenceCount:4,lastEvidenceAt:'2026-08-13T10:00:00.000Z'}]}
describe('institution student report snapshot',()=>{
  it('accepts an internally consistent identifier-minimal report',()=>{expect(institutionStudentReportSnapshotSchema.safeParse(snapshot).success).toBe(true);expect(JSON.stringify(snapshot)).not.toMatch(/memberRef|studentId|email|phone|note/)})
  it('rejects summary drift and extra identifier fields',()=>{expect(institutionStudentReportSnapshotSchema.safeParse({...snapshot,summary:{...snapshot.summary,outcomeCount:2}}).success).toBe(false);expect(institutionStudentReportSnapshotSchema.safeParse({...snapshot,memberRef:'a'.repeat(32)}).success).toBe(false)})
  it('preserves the analysis taxonomy version in a generated report',()=>{
    const analysis={classroom:{id:'11111111-1111-4111-8111-111111111111',name:'TYT A Sınıfı'},student:{memberRef:'a'.repeat(32),alias:'Öğrenci Bir',joinedAt:'2026-08-01T10:00:00.000Z'},scope:{game:'matematik',examRef:'TYT',taxonomyVersion:'ba-tyt-math-v2',modelVersion:'institution-evidence-v1',windowStart:'2026-08-01T10:00:00.000Z',windowEnd:'2026-08-14T10:00:00.000Z'},coverage:{supported:true,totalQuestions:120,mappedQuestions:120,percentage:100},summary:snapshot.summary,outcomes:[{code:'MAT-01',nodeCode:'ba-tyt-math-v2:outcome:mat-01',path:['TYT Matematik','Sayılar','Temel','Kavram'],title:'Temel Kavramlar',category:'sayilar',assessment:{outcomeCode:'MAT-01',status:'developing',score:62,confidence:'medium',evidence:{evidenceCount:8,independentEvidenceCount:4,firstEvidenceAt:'2026-08-02T10:00:00.000Z',lastEvidenceAt:'2026-08-13T10:00:00.000Z',windowStart:'2026-08-01T10:00:00.000Z',windowEnd:'2026-08-14T10:00:00.000Z',modelVersion:'institution-evidence-v1',taxonomyVersion:'ba-tyt-math-v2',coverageSupported:true}},details:{correctEvidenceCount:5,delayedCorrectCount:1,rawAccuracy:62,difficultyAccuracy:62,hintRate:0,fastWrongRate:0,components:{accuracy:62,delayedRetrieval:50,independence:80,selfRegulation:80}}}]}
    expect(buildInstitutionStudentReportSnapshot(analysis,{institutionName:'Bilge Pilot Kursu',teacherAlias:'Öğretmen Bir'})?.scope.taxonomyVersion).toBe('ba-tyt-math-v2')
  })
})
