-- Migration 177: privacy-by-default public leaderboard participation.
--
-- Public rankings are a separate disclosure purpose from profile discovery.
-- Every existing and new account therefore starts hidden until the user makes
-- an explicit leaderboard choice. Public delivery remains route-only so a
-- PostgREST caller cannot rebuild the ranking from profiles or weekly rows.
-- Rollout order is app first (routes fail closed while this column is absent),
-- then this migration, then the authenticated/public smoke matrix.

BEGIN;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS leaderboard_opt_in boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.profiles.leaderboard_opt_in IS
  'Explicit opt-in for public weekly/all-time leaderboard disclosure; default false for every account.';

CREATE INDEX IF NOT EXISTS idx_profiles_public_leaderboard_xp
  ON public.profiles (total_xp DESC, id)
  WHERE leaderboard_opt_in
    AND deleted_at IS NULL
    AND total_xp > 0;

-- Append-only evidence for preference changes. The trigger makes the profile
-- change and its evidence atomic; no browser role can read or write the log.
CREATE TABLE IF NOT EXISTS public.leaderboard_visibility_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  previous_visible boolean NOT NULL,
  new_visible boolean NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT leaderboard_visibility_events_changed
    CHECK (previous_visible IS DISTINCT FROM new_visible)
);

COMMENT ON TABLE public.leaderboard_visibility_events IS
  'Append-only evidence for explicit public leaderboard visibility changes.';

ALTER TABLE public.leaderboard_visibility_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.leaderboard_visibility_events
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.leaderboard_visibility_events TO service_role;

CREATE OR REPLACE FUNCTION public.audit_leaderboard_visibility_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
  IF OLD.leaderboard_opt_in IS DISTINCT FROM NEW.leaderboard_opt_in THEN
    INSERT INTO public.leaderboard_visibility_events(
      user_id,
      previous_visible,
      new_visible
    )
    VALUES (
      NEW.id,
      OLD.leaderboard_opt_in,
      NEW.leaderboard_opt_in
    );
  END IF;

  RETURN NEW;
END
$function$;

REVOKE ALL ON FUNCTION public.audit_leaderboard_visibility_change()
  FROM PUBLIC, anon, authenticated, service_role;

DROP TRIGGER IF EXISTS trg_audit_leaderboard_visibility_change ON public.profiles;
CREATE TRIGGER trg_audit_leaderboard_visibility_change
  AFTER UPDATE OF leaderboard_opt_in ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_leaderboard_visibility_change();

-- Profiles are already consumed through governed routes/RPCs. Remove both
-- table and historical column grants: a table-level REVOKE alone is not enough.
REVOKE SELECT ON TABLE public.profiles FROM PUBLIC, anon, authenticated;

DO $revoke_profile_columns$
DECLARE
  v_column record;
BEGIN
  FOR v_column IN
    SELECT attname
    FROM pg_attribute
    WHERE attrelid = 'public.profiles'::regclass
      AND attnum > 0
      AND NOT attisdropped
  LOOP
    EXECUTE format(
      'REVOKE SELECT (%I) ON TABLE public.profiles FROM PUBLIC, anon, authenticated',
      v_column.attname
    );
  END LOOP;
END
$revoke_profile_columns$;

-- Weekly rows and the ranked view are API-only. The service role applies the
-- public opt-in filter before returning the deliberately minimized payload.
DROP POLICY IF EXISTS "lb_select_all" ON public.leaderboard_weekly;
REVOKE SELECT ON TABLE public.leaderboard_weekly FROM PUBLIC, anon, authenticated;

DO $revoke_weekly_columns$
DECLARE
  v_column record;
BEGIN
  FOR v_column IN
    SELECT attname
    FROM pg_attribute
    WHERE attrelid = 'public.leaderboard_weekly'::regclass
      AND attnum > 0
      AND NOT attisdropped
  LOOP
    EXECUTE format(
      'REVOKE SELECT (%I) ON TABLE public.leaderboard_weekly FROM PUBLIC, anon, authenticated',
      v_column.attname
    );
  END LOOP;
END
$revoke_weekly_columns$;

CREATE OR REPLACE VIEW public.leaderboard_weekly_ranked
WITH (security_invoker = true)
AS
SELECT
  lw.id,
  lw.user_id,
  lw.week_start,
  lw.week_end,
  lw.xp_earned,
  lw.sessions_played,
  lw.correct_answers,
  lw.accuracy_pct,
  lw.rank,
  p.username,
  p.display_name,
  p.avatar_url,
  p.level_name,
  p.current_streak,
  RANK() OVER (
    PARTITION BY lw.week_start
    ORDER BY lw.xp_earned DESC
  ) AS current_rank
FROM public.leaderboard_weekly lw
JOIN public.profiles p ON p.id = lw.user_id
WHERE lw.week_start = date_trunc('week', now())::date
  AND p.leaderboard_opt_in
  AND p.deleted_at IS NULL
  AND p.username NOT LIKE '\_\_honeypot\_%\_\_' ESCAPE '\';

REVOKE ALL ON TABLE public.leaderboard_weekly_ranked
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.leaderboard_weekly_ranked TO service_role;

-- User search is already a server route. Move its invoker RPC behind that
-- route before removing the final profile read grant from browser roles.
REVOKE ALL ON FUNCTION public.search_profiles(text, uuid, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.search_profiles(text, uuid, integer)
  TO service_role;

DO $verify_private_leaderboard$
DECLARE
  v_has_client_profile_column boolean;
  v_has_client_weekly_column boolean;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute a
    JOIN pg_attrdef d
      ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = 'public.profiles'::regclass
      AND a.attname = 'leaderboard_opt_in'
      AND a.attnotnull
      AND pg_get_expr(d.adbin, d.adrelid) = 'false'
  ) THEN
    RAISE EXCEPTION '177 verification: leaderboard opt-in is not default-false and required';
  END IF;

  IF position('leaderboard_opt_in' IN pg_get_viewdef('public.leaderboard_weekly_ranked'::regclass, true)) = 0 THEN
    RAISE EXCEPTION '177 verification: weekly view is not opt-in filtered';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'public.profiles'::regclass
      AND attnum > 0
      AND NOT attisdropped
      AND (
        has_column_privilege('anon', 'public.profiles', attname, 'SELECT')
        OR has_column_privilege('authenticated', 'public.profiles', attname, 'SELECT')
      )
  ) INTO v_has_client_profile_column;

  IF v_has_client_profile_column THEN
    RAISE EXCEPTION '177 verification: a browser role can still read a profile column';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'public.leaderboard_weekly'::regclass
      AND attnum > 0
      AND NOT attisdropped
      AND (
        has_column_privilege('anon', 'public.leaderboard_weekly', attname, 'SELECT')
        OR has_column_privilege('authenticated', 'public.leaderboard_weekly', attname, 'SELECT')
      )
  ) INTO v_has_client_weekly_column;

  IF v_has_client_weekly_column THEN
    RAISE EXCEPTION '177 verification: a browser role can still read weekly rows';
  END IF;

  IF has_table_privilege('anon', 'public.leaderboard_weekly_ranked', 'SELECT')
     OR has_table_privilege('authenticated', 'public.leaderboard_weekly_ranked', 'SELECT') THEN
    RAISE EXCEPTION '177 verification: ranked view is still client-readable';
  END IF;

  IF NOT has_table_privilege('service_role', 'public.leaderboard_weekly_ranked', 'SELECT') THEN
    RAISE EXCEPTION '177 verification: service route lost ranked-view access';
  END IF;

  IF has_function_privilege('authenticated', 'public.search_profiles(text,uuid,integer)', 'EXECUTE')
     OR NOT has_function_privilege('service_role', 'public.search_profiles(text,uuid,integer)', 'EXECUTE') THEN
    RAISE EXCEPTION '177 verification: profile search RPC is not route-only';
  END IF;

  IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid = 'public.leaderboard_visibility_events'::regclass) THEN
    RAISE EXCEPTION '177 verification: visibility evidence RLS is disabled';
  END IF;
END
$verify_private_leaderboard$;

COMMIT;

NOTIFY pgrst, 'reload schema';
