#!/usr/bin/env bash
# =============================================================================
# Bilge Arena PostgREST env generator (idempotent)
# =============================================================================
# VPS uzerinde calistirilir: /opt/bilge-arena/secrets/postgrest.env uretir.
# Bu script repo'da committed - secret degerleri ICERMEZ.
# Calistirma: ssh root@VPS "bash /opt/bilge-arena/scripts/generate-postgrest-env.sh"
# =============================================================================

set -euo pipefail

SECRETS_DIR="/opt/bilge-arena/secrets"
DB_ENV="${SECRETS_DIR}/db.env"
TARGET="${SECRETS_DIR}/postgrest.env"

# Plan-deviation: Supabase JWKS URL (HS256 shared secret yerine ES256 asymmetric)
JWKS_URL="https://lvnmzdowhfzmpkueurih.supabase.co/auth/v1/.well-known/jwks.json"

if [[ ! -f "$DB_ENV" ]]; then
  echo "ERROR: $DB_ENV not found. Run init scripts first." >&2
  exit 1
fi

# Plan-deviation #11: db.env BILGE_ARENA_AUTH_PASSWORD kullaniyor (plan
# spec'inde APP_PWD/AUTH_PWD vardi, ama gercek env BILGE_ARENA_*_PASSWORD).
# shellcheck source=/dev/null
source "$DB_ENV"

if [[ -z "${BILGE_ARENA_AUTH_PASSWORD:-}" ]]; then
  echo "ERROR: BILGE_ARENA_AUTH_PASSWORD not set in $DB_ENV" >&2
  exit 1
fi
AUTH_PWD="${BILGE_ARENA_AUTH_PASSWORD}"

# JWKS URL erisim testi (PostgREST bunu fetch edebilecek mi?)
if ! curl -sSf "$JWKS_URL" -o /dev/null; then
  echo "ERROR: JWKS URL unreachable: $JWKS_URL" >&2
  exit 1
fi

# Dosyayi yaz (idempotent overwrite)
umask 077
cat > "$TARGET" <<EOF
# Generated by generate-postgrest-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. Production secrets.

PGRST_DB_URI=postgres://bilge_arena_authenticator:${AUTH_PWD}@panola-postgres:5432/bilge_arena_dev
PGRST_DB_SCHEMAS=public
PGRST_DB_ANON_ROLE=anon
PGRST_JWT_SECRET={"jwks_url":"${JWKS_URL}"}
PGRST_JWT_AUD=authenticated
PGRST_OPENAPI_MODE=ignore-privileges
PGRST_DB_USE_LEGACY_GUCS=false
PGRST_LOG_LEVEL=info
EOF
chmod 600 "$TARGET"

echo "OK: $TARGET written ($(wc -c < "$TARGET") bytes, mode 600)"
echo "JWKS URL: $JWKS_URL (verified reachable)"
