#!/usr/bin/env bash
# =============================================================================
# Bilge Arena Realtime env generator (idempotent)
# =============================================================================
# VPS uzerinde calistirilir: /opt/bilge-arena/secrets/realtime.env uretir.
# Bu script repo'da committed - secret degerleri ICERMEZ.
# Calistirma: ssh root@VPS "bash /opt/bilge-arena/scripts/generate-realtime-env.sh"
#
# Idempotency: ESKI realtime.env varsa DB_ENC_KEY/API_JWT_SECRET/SECRET_KEY_BASE
# DEGERLERINI YENIDEN UReTMEZ (eski tenant verisi DB_ENC_KEY ile sifrelenmis;
# kaybolursa _realtime.tenants tablosundaki tenant kayitlari okunamaz hale
# gelir). Sadece DB_PASSWORD ve degisken parametreleri gunceller.
# =============================================================================

set -euo pipefail

SECRETS_DIR="/opt/bilge-arena/secrets"
DB_ENV="${SECRETS_DIR}/db.env"
TARGET="${SECRETS_DIR}/realtime.env"

if [[ ! -f "$DB_ENV" ]]; then
  echo "ERROR: $DB_ENV not found. Run init scripts first." >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$DB_ENV"

if [[ -z "${BILGE_ARENA_AUTH_PASSWORD:-}" ]]; then
  echo "ERROR: BILGE_ARENA_AUTH_PASSWORD not set in $DB_ENV" >&2
  exit 1
fi
AUTH_PWD="${BILGE_ARENA_AUTH_PASSWORD}"

# Plan-deviation #13: bilge-arena-internal HS256 secret (Realtime v2.30.34
# JWKS desteklemiyor). Channel-auth tokenlari Next.js /api/realtime/token
# tarafindan bu secret ile imzalanir (Sprint 1 PR3).
#
# Idempotency: Eski realtime.env varsa DB_ENC_KEY/API_JWT_SECRET/
# SECRET_KEY_BASE'i KORU. Aksi takdirde:
#   - DB_ENC_KEY rotate -> _realtime.tenants tablosundaki sifrelenmis ext field
#                          decrypt edilemez (Realtime tenant lookup fail)
#   - API_JWT_SECRET rotate -> aktif client tokenlari invalid olur
#   - SECRET_KEY_BASE rotate -> Phoenix session/cookie invalidation
extract_existing() {
  local key="$1"
  if [[ -f "$TARGET" ]]; then
    grep -E "^${key}=" "$TARGET" | head -1 | cut -d= -f2- || true
  fi
}

DB_ENC_KEY="$(extract_existing DB_ENC_KEY)"
# Plan-deviation #15: DB_ENC_KEY 16 RAW BYTE (ASCII string) olmalidir.
# Realtime aes_128_ecb cagiriyor, env degerini olduğu gibi key olarak veriyor
# (hex decode YOK). 32 hex char => 32 byte => "Bad key size" crash.
# openssl rand -base64 12 => 16 char (padding'siz) => 16 byte raw.
# Eski (hatali) deger varsa REJECT et, regenerate.
if [[ -n "$DB_ENC_KEY" && ${#DB_ENC_KEY} -ne 16 ]]; then
  echo "WARN: Existing DB_ENC_KEY length=${#DB_ENC_KEY} (need 16). Regenerating."
  DB_ENC_KEY=""
fi
if [[ -z "$DB_ENC_KEY" ]]; then
  DB_ENC_KEY="$(openssl rand -base64 12)"
  echo "INFO: Generated new DB_ENC_KEY (16 chars base64, AES-128 raw key)"
else
  echo "INFO: Reused existing DB_ENC_KEY (16 chars, idempotent)"
fi

API_JWT_SECRET="$(extract_existing API_JWT_SECRET)"
if [[ -z "$API_JWT_SECRET" ]]; then
  API_JWT_SECRET="$(openssl rand -hex 32)"
  echo "INFO: Generated new API_JWT_SECRET (32 bytes hex)"
else
  echo "INFO: Reused existing API_JWT_SECRET (idempotent)"
fi

SECRET_KEY_BASE="$(extract_existing SECRET_KEY_BASE)"
if [[ -z "$SECRET_KEY_BASE" ]]; then
  SECRET_KEY_BASE="$(openssl rand -hex 32)"
  echo "INFO: Generated new SECRET_KEY_BASE (32 bytes hex)"
else
  echo "INFO: Reused existing SECRET_KEY_BASE (idempotent)"
fi

# Dosyayi yaz (idempotent overwrite, secrets korundu)
umask 077
cat > "$TARGET" <<EOF
# Generated by generate-realtime-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. Production secrets.
# Plan-deviation #12: wal_level=logical degisikligi koordineli Panola restart
#   penceresinde yapilacak. Sprint 0 Broadcast+Presence ile shipping (postgres_
#   changes ozelligi yok).
# Plan-deviation #13: API_JWT_SECRET = bilge-arena-internal HS256 (Realtime
#   JWKS desteklemiyor). Channel-auth: Next.js /api/realtime/token RPC.
# Plan-deviation #14: ECTO_IPV6=false override (image defaults to IPv6,
#   panola-network IPv4-only).

DB_HOST=panola-postgres
DB_PORT=5432
DB_NAME=bilge_arena_dev
DB_USER=bilge_arena_authenticator
DB_PASSWORD=${AUTH_PWD}
DB_AFTER_CONNECT_QUERY=SET search_path TO _realtime
DB_ENC_KEY=${DB_ENC_KEY}
API_JWT_SECRET=${API_JWT_SECRET}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
ERL_AFLAGS=-proto_dist inet_tcp
ECTO_IPV6=false
DNS_NODES=
RLIMIT_NOFILE=10000
APP_NAME=bilge-arena-realtime
SEED_SELF_HOST=true
RUN_JANITOR=true
EOF
chmod 600 "$TARGET"

echo "OK: $TARGET written ($(wc -c < "$TARGET") bytes, mode 600)"
echo "Secrets: DB_ENC_KEY (16B), API_JWT_SECRET (32B), SECRET_KEY_BASE (32B)"
echo "Tenant: APP_NAME=bilge-arena-realtime, SEED_SELF_HOST=true"
