#!/usr/bin/env bash
# =============================================================================
# Bilge Arena Realtime env generator (idempotent)
# =============================================================================
# VPS uzerinde calistirilir: /opt/bilge-arena/secrets/realtime.env uretir.
# Bu script repo'da committed - secret degerleri ICERMEZ.
# Calistirma: ssh root@VPS "bash /opt/bilge-arena/scripts/generate-realtime-env.sh"
#
# Idempotency: ESKI realtime.env varsa DB_ENC_KEY/API_JWT_SECRET/SECRET_KEY_BASE/
# RELEASE_COOKIE/METRICS_JWT_SECRET DEGERLERINI YENIDEN URETMEZ (eski tenant verisi
# DB_ENC_KEY ile sifrelenmis; kaybolursa _realtime.tenants kayitlari okunamaz hale
# gelir). Sadece DB_PASSWORD ve degisken parametreleri gunceller.
#
# 2026-10-04 (supabase/realtime v2.30.34 -> v2.140.7, not #101797 GHSA-9vjf):
#   - METRICS_JWT_SECRET: v2.140'ta zorunlu (yoksa boot'ta System.EnvError).
#   - SELF_HOST_TENANT_NAME=ws-dev: Realtime tenant'i Host basliginin ilk
#     etiketinden cozer (ws-dev.bilgearena.com -> "ws-dev"). Eski "realtime-dev"
#     tenant adi yuzunden her baglanti TenantNotFound aliyordu.
#   - CLUSTER_STRATEGIES=NONE: tek dugum. Varsayilan POSTGRES stratejisi
#     RELEASE_COOKIE'yi LISTEN kanal adi yapar; 64 karakter > 63 sinir -> crash.
#   - GEN_RPC_SOCKET_IP=127.0.0.1: dugumler arasi RPC (5369) yalniz loopback
#     (ir-20261003 epmd/dist loopback kararinin devami).
#   - DB_USER=bilge_arena_realtime: REPLICATION yetkili ayri rol; _realtime ve
#     realtime semalarinin sahibi (tenant migration'lari ALTER ister).
#   - postgres_changes ACIK (4 Ekim ikinci adim): bilge-arena-db artik Dockerfile.db ile
#     postgres:16-alpine + wal2json; output_plugin_libraries=wal2json. Tenant migration'lari
#     icin rol: CREATEROLE, createrole_self_grant='set, inherit', supabase_admin/postgres/
#     dashboard_user (NOLOGIN) uyeligi WITH SET, GRANT SET ON PARAMETER log_min_messages.
# =============================================================================

set -euo pipefail

SECRETS_DIR="/opt/bilge-arena/secrets"
DB_ENV="${SECRETS_DIR}/db.env"
TARGET="${SECRETS_DIR}/realtime.env"

if [[ ! -f "$DB_ENV" ]]; then
  echo "ERROR: $DB_ENV not found. Run init scripts first." >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$DB_ENV"

if [[ -z "${BILGE_ARENA_REALTIME_PASSWORD:-}" ]]; then
  echo "ERROR: BILGE_ARENA_REALTIME_PASSWORD not set in $DB_ENV (role bilge_arena_realtime)" >&2
  exit 1
fi
RT_PWD="${BILGE_ARENA_REALTIME_PASSWORD}"

extract_existing() {
  local key="$1"
  if [[ -f "$TARGET" ]]; then
    grep -E "^${key}=" "$TARGET" | head -1 | cut -d= -f2- || true
  fi
}

# Plan-deviation #15: DB_ENC_KEY = 16 raw ASCII bytes (NOT 32 hex chars).
DB_ENC_KEY="$(extract_existing DB_ENC_KEY)"
if [[ -n "$DB_ENC_KEY" && ${#DB_ENC_KEY} -ne 16 ]]; then
  echo "WARN: Existing DB_ENC_KEY length=${#DB_ENC_KEY} (need 16). Regenerating."
  DB_ENC_KEY=""
fi
if [[ -z "$DB_ENC_KEY" ]]; then
  DB_ENC_KEY="$(openssl rand -base64 12)"
  echo "INFO: Generated new DB_ENC_KEY (16 chars base64, AES-128 raw key)"
else
  echo "INFO: Reused existing DB_ENC_KEY (16 chars, idempotent)"
fi

API_JWT_SECRET="$(extract_existing API_JWT_SECRET)"
if [[ -z "$API_JWT_SECRET" ]]; then
  API_JWT_SECRET="$(openssl rand -hex 32)"
  echo "INFO: Generated new API_JWT_SECRET (32 bytes hex)"
else
  echo "INFO: Reused existing API_JWT_SECRET (idempotent)"
fi

SECRET_KEY_BASE="$(extract_existing SECRET_KEY_BASE)"
if [[ -z "$SECRET_KEY_BASE" ]]; then
  SECRET_KEY_BASE="$(openssl rand -hex 32)"
  echo "INFO: Generated new SECRET_KEY_BASE (32 bytes hex)"
else
  echo "INFO: Reused existing SECRET_KEY_BASE (idempotent)"
fi

# Prometheus /metrics ucu icin bearer sirri (v2.140 zorunlu). Disaridan erisim yok;
# yalniz zorunlu oldugu icin uretilir ve korunur.
METRICS_JWT_SECRET="$(extract_existing METRICS_JWT_SECRET)"
if [[ -z "$METRICS_JWT_SECRET" ]]; then
  METRICS_JWT_SECRET="$(openssl rand -hex 32)"
  echo "INFO: Generated new METRICS_JWT_SECRET (32 bytes hex)"
else
  echo "INFO: Reused existing METRICS_JWT_SECRET (idempotent)"
fi

# ir-20261003 (disc #2086 / #2099): Erlang dagitim cookie'si imaj varsayilani
# (/app/releases/COOKIE, herkese acik) OLMASIN. Mevcut degeri KORU (idempotent),
# yoksa uret. Rotasyon istenirse realtime.env'den satiri sil ve yeniden calistir.
RELEASE_COOKIE="$(extract_existing RELEASE_COOKIE)"
if [[ -z "$RELEASE_COOKIE" ]]; then
  RELEASE_COOKIE="$(openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c 64)"
  echo "INFO: Generated new RELEASE_COOKIE (64 chars)"
else
  echo "INFO: Reused existing RELEASE_COOKIE (idempotent)"
fi

# Dosyayi yaz (idempotent overwrite, secrets korundu)
umask 077
cat > "$TARGET" <<EOF
# Generated by generate-realtime-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. Production secrets.
# Plan-deviation #13: API_JWT_SECRET = bilge-arena-internal HS256 (Realtime
#   JWKS desteklemiyor). Channel-auth: Next.js /api/realtime/token RPC;
#   Vercel BILGE_ARENA_REALTIME_JWT_SECRET bu degerle AYNI olmali.
# Plan-deviation #14: ECTO_IPV6=false override (image defaults to IPv6).
# 2026-10-04: postgres_changes acik (wal2json imaji), broadcast+presence+postgres_changes.

DB_HOST=bilge-arena-db
DB_PORT=5432
DB_NAME=bilge_arena_dev
DB_USER=bilge_arena_realtime
DB_PASSWORD=${RT_PWD}
DB_AFTER_CONNECT_QUERY=SET search_path TO _realtime
DB_ENC_KEY=${DB_ENC_KEY}
API_JWT_SECRET=${API_JWT_SECRET}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
METRICS_JWT_SECRET=${METRICS_JWT_SECRET}
# ir-20261003: epmd ve dist portu yalniz loopback (node adi @127.0.0.1, env.sh).
# RELEASE_DISTRIBUTION=none env'den CALISMAZ: imajin env.sh'i name'i kosulsuz export eder.
ERL_AFLAGS=-proto_dist inet_tcp -kernel inet_dist_use_interface {127,0,0,1}
ERL_EPMD_ADDRESS=127.0.0.1
RELEASE_COOKIE=${RELEASE_COOKIE}
GEN_RPC_SOCKET_IP=127.0.0.1
CLUSTER_STRATEGIES=NONE
ECTO_IPV6=false
RLIMIT_NOFILE=10000
APP_NAME=bilge-arena-realtime
SEED_SELF_HOST=true
SELF_HOST_TENANT_NAME=ws-dev
RUN_JANITOR=true
EOF
chmod 600 "$TARGET"

echo "OK: $TARGET written ($(wc -c < "$TARGET") bytes, mode 600)"
echo "Secrets: DB_ENC_KEY (16B), API_JWT_SECRET (32B), SECRET_KEY_BASE (32B), METRICS_JWT_SECRET (32B), RELEASE_COOKIE (64)"
echo "Tenant: SELF_HOST_TENANT_NAME=ws-dev, DB_USER=bilge_arena_realtime, CLUSTER_STRATEGIES=NONE"
