#!/usr/bin/env bash
# =============================================================================
# Bilge Arena PostgREST env generator (idempotent)
# =============================================================================
# VPS uzerinde calistirilir: /opt/bilge-arena/secrets/postgrest.env uretir.
# Bu script repo'da committed - secret degerleri ICERMEZ.
# Calistirma: ssh root@VPS "bash /opt/bilge-arena/scripts/generate-postgrest-env.sh"
#
# 2026-10-04 (disc #2130): PostgREST hicbir surumde (v12-v16) jwt-secret icinde
# bir "jwks_url" alanini fetch ETMEZ; jwt-secret ya duz HS256 sirri ya da
# dogrudan JWK / JWK Set JSON'udur. Eski {"jwks_url": ...} degeri Supabase'in
# ES256 access token'larini her zaman 401'e dusuruyordu. Artik JWKS burada
# cekilir, dogrulanir ve anahtar seti dogrudan PGRST_JWT_SECRET'a yazilir.
# Supabase imzalama anahtari dondurulurse bu script yeniden calistirilip
# konteyner yeniden olusturulur (docker compose -f docker-compose.rooms.yml
# up -d --no-deps postgrest).
# =============================================================================

set -euo pipefail

SECRETS_DIR="/opt/bilge-arena/secrets"
DB_ENV="${SECRETS_DIR}/db.env"
TARGET="${SECRETS_DIR}/postgrest.env"

# Supabase JWKS (ES256 asymmetric; HS256 shared secret kullanilmaz)
JWKS_URL="https://lvnmzdowhfzmpkueurih.supabase.co/auth/v1/.well-known/jwks.json"

if [[ ! -f "$DB_ENV" ]]; then
  echo "ERROR: $DB_ENV not found. Run init scripts first." >&2
  exit 1
fi

# Plan-deviation #11: db.env BILGE_ARENA_AUTH_PASSWORD kullaniyor (plan
# spec'inde APP_PWD/AUTH_PWD vardi, ama gercek env BILGE_ARENA_*_PASSWORD).
# shellcheck source=/dev/null
source "$DB_ENV"

if [[ -z "${BILGE_ARENA_AUTH_PASSWORD:-}" ]]; then
  echo "ERROR: BILGE_ARENA_AUTH_PASSWORD not set in $DB_ENV" >&2
  exit 1
fi
AUTH_PWD="${BILGE_ARENA_AUTH_PASSWORD}"

# JWKS'i cek ve dogrula: en az bir anahtar, her anahtarda kty+kid, yalniz
# asimetrik imza anahtarlari. Cikti tek satir kompakt JSON (env dosyasi icin).
JWKS_RAW="$(curl -sSf --max-time 15 "$JWKS_URL")" || {
  echo "ERROR: JWKS fetch failed: $JWKS_URL" >&2
  exit 1
}
JWKS_COMPACT="$(printf '%s' "$JWKS_RAW" | python3 -c '
import json, sys
doc = json.load(sys.stdin)
keys = doc.get("keys")
if not isinstance(keys, list) or not keys:
    sys.exit("JWKS has no keys")
for k in keys:
    if k.get("kty") not in ("EC", "RSA"):
        sys.exit("unexpected kty in JWKS: %r" % k.get("kty"))
    if not k.get("kid"):
        sys.exit("JWKS key without kid")
    if k.get("use", "sig") != "sig":
        sys.exit("JWKS key not for signatures")
print(json.dumps({"keys": keys}, separators=(",", ":")))
')" || {
  echo "ERROR: JWKS validation failed" >&2
  exit 1
}
KIDS="$(printf '%s' "$JWKS_COMPACT" | python3 -c 'import json,sys; print(",".join(k["kid"] for k in json.load(sys.stdin)["keys"]))')"

# Dosyayi yaz (idempotent overwrite). PGRST_DB_USE_LEGACY_GUCS PostgREST 12.0'da
# kaldirildi; artik yazilmaz.
umask 077
cat > "$TARGET" <<EOF
# Generated by generate-postgrest-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. Production secrets.
# JWKS source: ${JWKS_URL}
# JWKS kids: ${KIDS}

PGRST_DB_URI=postgres://bilge_arena_authenticator:${AUTH_PWD}@bilge-arena-db:5432/bilge_arena_dev
PGRST_DB_SCHEMAS=public
PGRST_DB_ANON_ROLE=anon
PGRST_JWT_SECRET=${JWKS_COMPACT}
PGRST_JWT_AUD=authenticated
PGRST_OPENAPI_MODE=ignore-privileges
PGRST_LOG_LEVEL=info
EOF
chmod 600 "$TARGET"

echo "OK: $TARGET written ($(wc -c < "$TARGET") bytes, mode 600)"
echo "JWKS: $JWKS_URL embedded as JWK Set (kids: $KIDS)"
