import {readFile} from 'node:fs/promises'
import {describe,expect,it} from 'vitest'

const migration=new URL('../migrations/211_institution_program_completion_integrity.sql',import.meta.url)
describe('forward institution completion contract',()=>{
  it('keeps observational review distinct from all trusted tasks',async()=>{
    const sql=await readFile(migration,'utf8')
    expect(sql).toContain('program.item_count>0')
    expect(sql).toContain('WHERE item.program_id=program.id)=program.item_count')
    expect(sql).toContain("item.status<>'completed'")
    expect(sql).toContain('execution.student_id=program.student_id AND execution.task_type=item.task_type')
    expect(sql).toContain('execution.completed_at=item.completed_at')
    expect(sql).toContain('execution.question_exam_ref IS NOT DISTINCT FROM program.question_exam_ref')
    expect(sql).toContain('execution.taxonomy_version=program.taxonomy_version')
    expect(sql).toContain('attempt.started_at>=execution.started_at AND attempt.completed_at=execution.completed_at')
    expect(sql).toContain('session.started_at>=execution.started_at AND session.completed_at=execution.completed_at')
    expect(sql).toContain('NOT COALESCE(answer.is_skipped,false)')
    expect(sql).toContain('review.membership_id=program.membership_id')
    const review=sql.slice(sql.indexOf('CREATE OR REPLACE FUNCTION public.review_institution_study_program('))
    expect(review).not.toContain('free_pilot_legacy_program_review(')
    expect(review).toContain('public.institution_study_program_review_ready(v_program.id,v_today)')
    expect(review).toContain("'programStatus',v_program.status")
    expect(review).toContain("RETURN v_request.result||jsonb_build_object('replayed',true)")
    expect(review).toContain("operation='review_study_program' AND request_id=p_request_id FOR UPDATE")
    expect(review).toContain('v_request.payload_hash<>v_hash')
    expect(review).toContain('classroom.teacher_id=p_user_id')
    expect(review).toContain('public.institution_pilot_assert_operational_actor(p_user_id)')
    expect(review.indexOf("hashtextextended('institution-program-execution-integrity-v201',201)")).toBeLessThan(review.indexOf('FOR UPDATE OF program'))
  })
  it('preserves closed ACLs, lifecycle, deferred invariants and fails on historical drift',async()=>{
    const sql=await readFile(migration,'utf8')
    expect(sql).toContain("IF NOT FOUND OR v_program.status<>'published' THEN RETURN")
    expect(sql).toContain("profile.deleted_at IS NULL")
    expect(sql).toContain('public.institution_pilot_is_operational(v_program.institution_id)')
    expect(sql).toContain('NOT public.teacher_classroom_is_blocked(classroom.teacher_id,v_program.student_id)')
    expect(sql.match(/DEFERRABLE INITIALLY DEFERRED/g)).toHaveLength(4)
    expect(sql).toContain('ARRAY[v_old_id,v_new_id]')
    expect(sql).toContain('ORDER BY parent_id')
    expect(sql).toContain('migration 211 precheck: % completed programs lack full trusted execution')
    expect(sql).toContain('migration 211 postcheck: private completion helper leaked')
    expect(sql).toContain('migration 211 postcheck: review RPC ACL mismatch')
    expect(sql).toContain('migration 211 postcheck: completion trigger mismatch')
    expect(sql).toContain('FROM PUBLIC,anon,authenticated,service_role;')
    expect(sql).toContain('GRANT EXECUTE ON FUNCTION public.review_institution_study_program(uuid,text,text,text,uuid) TO service_role;')
    expect(sql).not.toMatch(/GRANT.*ON TABLE/)
    expect(sql).not.toMatch(/DISABLE TRIGGER/)
  })
})
