import {describe,it,expect} from 'vitest'; import {readFileSync} from 'node:fs'; import {dirname,join} from 'node:path'; import {fileURLToPath} from 'node:url';
const sql=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'..','migrations','104_paper_study_packs.sql'),'utf8');
describe('104 paper packs SQL contract',()=>{
 it('is private, RLS, service-RPC-only and seven-day snapshot based',()=>{expect(sql.match(/ENABLE ROW LEVEL SECURITY/g)).toHaveLength(5);expect(sql).toMatch(/FROM PUBLIC,anon,authenticated,service_role/);expect(sql).toMatch(/clock_timestamp\(\)\+interval '7 days'/);expect(sql).toMatch(/GRANT EXECUTE ON FUNCTION[\s\S]*TO service_role/)});
 it('keeps active answer keys private and grades snapshots server side',()=>{expect(sql).toMatch(/jsonb_build_object\('question',q\.content->'question','options',q\.content->'options'/);expect(sql).toMatch(/q\.content->>'answer'/);expect(sql).toMatch(/CASE WHEN p\.status='submitted' THEN i\.correct_option ELSE NULL END/);expect(sql).toMatch(/selected_option IS NOT NULL/);expect(sql).toMatch(/\.5\*o\.mapping_weight/)});
 it('fails closed when a plan question cannot satisfy the public snapshot contract',()=>{expect(sql).toMatch(/q\.game=dp\.game/);expect(sql).toMatch(/char_length\(btrim\(q\.content->>'question'\)\) BETWEEN 1 AND 20000/);expect(sql).toMatch(/jsonb_array_length\(q\.content->'options'\) BETWEEN 2 AND 10/);expect(sql).toMatch(/char_length\(o#>>'\{\}'\)>10000/);expect(sql).toMatch(/char_length\(q\.content->>'passage'\)<=50000/);expect(sql).toMatch(/char_length\(q\.category\)<=120/)});
 it('has strict canonical questionId answers and out-of-order-safe paper mastery',()=>{expect(sql).toMatch(/questionId' AND a \? 'selectedOptionIndex/);expect(sql).toMatch(/WHEN jsonb_typeof\(a\)<>'object' THEN true[\s\S]*jsonb_object_keys/);expect(sql).toMatch(/lower\(i\.question_id::text\)=lower\(a->>'questionId'\)/);expect(sql).not.toMatch(/\(a->>'questionId'\)::uuid/);expect(sql).toMatch(/WHEN jsonb_typeof\(a->'selectedOptionIndex'\)='number'[\s\S]*jsonb_array_length/);expect(sql).toMatch(/jsonb_array_length\(q\.content->'options'\) BETWEEN 2 AND 10/);expect(sql).toMatch(/r\.user_id IS DISTINCT FROM p_user_id/);expect(sql).toMatch(/GREATEST\(COALESCE\(public\.user_outcome_state\.last_answered_at/)});
 it('has owner/replay/expiry and zero reward contracts',()=>{expect(sql).toMatch(/paper pack owner mismatch/);expect(sql).toMatch(/payload mismatch/);expect(sql).toMatch(/paper pack expired/);expect(sql).toMatch(/'xp',0,'coins',0,'socialPoints',0/);expect(sql).not.toMatch(/INSERT INTO public\.(?:verified_attempts|game_sessions|session_answers|reward_ledger|weekly_learning_league_contributions)/)});
});
