import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const sql = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'migrations', '106_question_content_governance.sql'), 'utf8')
const body = (name, next = 'REVOKE ALL ON FUNCTION') => {
  const start = sql.indexOf(`CREATE OR REPLACE FUNCTION public.${name}`)
  const end = sql.indexOf(next, start + 1)
  expect(start).toBeGreaterThanOrEqual(0); expect(end).toBeGreaterThan(start)
  return sql.slice(start, end)
}

describe('106 question content governance SQL contract', () => {
  it('creates the private immutable governance, appeal, snapshot, correction and psychometric stores', () => {
    const tables = ['content_governance_runtime','content_governance_requests','question_content_revisions','question_revision_outcomes','question_revision_sources','question_revision_approvals','question_governance_events','question_appeals','question_appeal_events','verified_attempt_question_revisions','question_error_incidents','question_result_corrections','question_revision_psychometrics']
    for (const table of tables) { expect(sql).toContain(`CREATE TABLE IF NOT EXISTS public.${table}`); expect(sql).toContain(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY`) }
    expect(sql).toMatch(/REVOKE ALL ON TABLE[\s\S]+FROM PUBLIC,anon,authenticated,service_role/)
    expect(sql).toContain('ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS published_revision_id')
    expect(sql).toContain("change_kind IN ('legacy_import','create','edit','correct_answer','retire')")
    expect(sql).toContain("status IN ('draft','stage1_approved','stage2_approved','published','rejected','superseded')")
  })
  it('seeds separated permissions and enforces fixed-path service-only RPCs', () => {
    for (const permission of ['content.prepare','content.review.stage1','content.review.stage2','content.publish','content.appeals.manage','content.corrections.apply','content.psychometrics.refresh','content.enforcement.manage']) expect(sql).toContain(`'${permission}'`)
    expect(sql.match(/SECURITY DEFINER SET search_path = pg_catalog/g).length).toBeGreaterThanOrEqual(17)
    expect(sql).toMatch(/GRANT EXECUTE ON FUNCTION[\s\S]+ TO service_role/)
    expect(sql).not.toMatch(/GRANT EXECUTE[\s\S]+TO (?:anon|authenticated)/)
  })
  it('fails closed against direct mutation and snapshots verified attempts before correction eligibility', () => {
    expect(sql).toContain('trg_question_content_direct_mutation_guard')
    expect(sql).toContain('trg_question_direct_insert_guard')
    expect(sql).toContain('direct question content or activation mutation is disabled')
    expect(sql).toContain('direct question insert is disabled; create a governed draft')
    expect(sql).toContain('CREATE OR REPLACE FUNCTION public.set_content_governance_enforcement')
    expect(sql).toContain('CREATE OR REPLACE FUNCTION public.get_content_governance_enforcement')
    expect(sql).toContain('enforce_direct_mutation boolean NOT NULL DEFAULT false')
    expect(sql).toContain('COALESCE((SELECT enforce_direct_mutation FROM public.content_governance_runtime WHERE singleton),true)')
    expect(sql).toContain('CREATE OR REPLACE FUNCTION public.create_governed_question')
    expect(sql).toContain('trg_snapshot_verified_attempt_revisions')
    expect(sql).toContain('trg_validate_and_bind_verified_completion_revisions')
    expect(sql).toContain('verified completion does not match immutable revision snapshot')
    expect(sql).toContain('verified completion score does not match immutable revision snapshot')
    expect(sql).toContain('question_revision_id=s.revision_id')
  })
  it('returns canonical private issuance snapshots for both verified issuance paths', () => {
    expect(sql).toContain('CREATE OR REPLACE FUNCTION public.verified_attempt_private_snapshot')
    expect(sql).toContain('CREATE OR REPLACE FUNCTION public.verified_exam_private_snapshot')
    expect(sql).toMatch(/'snapshot',public\.verified_attempt_private_snapshot\(v_attempt_id\)/)
    expect(sql).toMatch(/'snapshot',public\.verified_exam_private_snapshot\(v_attempt\)/)
    expect(sql).toContain('get_verified_attempt_question_snapshots(p_attempt_id uuid,p_user_id uuid,p_require_active boolean)')
    expect(sql).toContain('verified attempt owner mismatch')
    expect(sql).toContain('verified attempt is inactive')
    expect(sql).toContain('verified attempt is expired before completion')
    for (const key of ['questionId','revisionId','contentSha256','content','correctOption','difficulty','basePoints']) expect(sql).toContain(`'${key}'`)
  })
  it('requires independent two-stage approval and stale-base protected publication', () => {
    const requestLock = body('content_governance_lock_request', 'CREATE OR REPLACE FUNCTION public.content_governance_has_permission')
    const create = body('create_question_content_revision', 'CREATE OR REPLACE FUNCTION public.review_question_content_revision')
    const review = body('review_question_content_revision', 'CREATE OR REPLACE FUNCTION public.publish_question_content_revision')
    const publish = body('publish_question_content_revision', 'CREATE OR REPLACE FUNCTION public.quarantine_question_content')
    expect(requestLock).toContain('pg_advisory_xact_lock')
    expect(create).toContain("content_governance_lock_request(p_user_id,'create_revision',p_request_id)")
    expect(create).toContain("jsonb_build_object('questionId',p_question_id,'baseRevisionId',p_base_revision_id,'payload',p_payload)")
    expect(review).toContain("content_governance_lock_request(p_user_id,'review_revision',p_request_id)")
    expect(review).toContain('r.prepared_by=p_user_id')
    expect(review).toContain('independent stage one approval required')
    expect(publish).toContain('independent approvals required')
    expect(publish).toContain('stale revision cannot publish')
    expect(publish).toContain("UPDATE public.question_content_revisions SET status='superseded'")
  })
  it('keeps appeals owner-bound and corrections append-only without reward or mastery writes', () => {
    const submit = body('submit_question_appeal', 'CREATE OR REPLACE FUNCTION public.get_my_question_appeals')
    const adminQueue = body('get_question_appeal_queue', 'CREATE OR REPLACE FUNCTION public.resolve_question_appeal')
    const createIncident = body('create_question_error_incident', 'CREATE OR REPLACE FUNCTION public.apply_question_result_corrections')
    const apply = body('apply_question_result_corrections', 'CREATE OR REPLACE FUNCTION public.get_my_question_result_corrections')
    expect(submit).toContain('appeal answer owner mismatch')
    expect(submit).toContain("content_governance_lock_request(p_user_id,'submit_appeal',p_request_id)")
    expect(adminQueue).toContain("content_governance_has_permission(p_user_id,'content.appeals.manage')")
    expect(adminQueue).toContain("'hasSessionEvidence'")
    expect(adminQueue).not.toContain("'userId'")
    expect(adminQueue).not.toContain("'sessionAnswerId'")
    expect(adminQueue).toContain("'nextCursor'")
    expect(sql).toContain('legacy_error_report_id uuid UNIQUE REFERENCES public.error_reports(id)')
    expect(sql).toContain('ON CONFLICT(legacy_error_report_id) DO NOTHING')
    expect(sql).toContain("e.status::text='pending'")
    expect(sql).toContain("session_answer_id,revision_id,reason_code")
    expect(sql).toContain("interval '48 hours'")
    expect(sql).toContain("interval '14 days'")
    expect(sql).toContain("'acknowledgmentDueAt'")
    expect(sql).toContain("'resolutionDueAt'")
    expect(apply).toContain("i.error_type<>'wrong_key'")
    expect(createIncident).toContain("'eligibleCount'")
    expect(createIncident).toContain("'manualRequiredCount'")
    expect(createIncident).toContain("e.status IN ('published','superseded')")
    expect(apply).toContain("JOIN public.game_sessions gs ON gs.id=a.session_id AND gs.status='completed'")
    expect(apply).toContain('ON CONFLICT(incident_id,session_answer_id) DO NOTHING')
    expect(sql).not.toMatch(/(?:INSERT INTO|UPDATE|DELETE FROM) public\.(?:reward_ledger|xp_log|user_outcome_state|mastery_outcome_evidence|review_cards|review_logs|weekly_learning_league_contributions)/i)
  })
  it('keeps options in the existing public grade/session 2..5 and 0..4 envelope', () => {
    const validate = body('content_governance_validate_payload', 'CREATE OR REPLACE FUNCTION public.tg_question_content_direct_mutation_guard')
    expect(sql).toContain("jsonb_array_length(v_content->'options') NOT BETWEEN 2 AND 5")
    expect(sql).toContain("correct_option smallint NOT NULL CHECK (correct_option BETWEEN 0 AND 4)")
    expect(sql).toContain('106 preflight failed: existing question option/answer shape is incompatible')
    expect(validate).toContain("ARRAY['outcomeId','primary','weight']")
    expect(validate).toContain("jsonb_typeof(o->'primary') IS DISTINCT FROM 'boolean') <> 0")
  })
  it('returns the exact API queue/detail envelopes and accepts every content-quality reader permission', () => {
    const queue = body('get_question_content_governance_queue', 'CREATE OR REPLACE FUNCTION public.get_question_content_revision')
    const detail = body('get_question_content_revision', 'ALTER TABLE public.content_governance_requests')
    expect(queue).toContain("'items'")
    expect(queue).toContain("'nextCursor',CASE WHEN")
    expect(queue).toContain('(r.prepared_at,r.id)<(v_cursor_time,v_cursor_id)')
    expect(queue).toContain('invalid governance queue cursor')
    expect(queue).toContain("'createdAt'")
    for (const permission of ['content.appeals.manage','content.corrections.apply','content.psychometrics.refresh']) expect(queue).toContain(permission)
    expect(detail).toContain("'revision',jsonb_build_object")
    expect(detail).toContain("'outcomes',COALESCE")
    expect(detail).toContain("'psychometrics',COALESCE")
    expect(detail).toContain("'incidents',COALESCE")
    expect(detail).toContain("'provenanceRef',s.provenance_ref")
    expect(detail).toContain("RAISE EXCEPTION 'revision not found' USING ERRCODE='P0002'")
    expect(sql).toContain('CREATE OR REPLACE FUNCTION public.get_published_question_content_revision')
  })
  it('limits psychometrics to verified completed revision snapshots and suppresses low-n discrimination', () => {
    const psych = body('materialize_question_revision_psychometrics', 'CREATE OR REPLACE FUNCTION public.get_question_content_governance_queue')
    expect(psych).toContain('JOIN public.verified_attempts')
    expect(psych).toContain('JOIN public.verified_attempt_question_revisions snap')
    expect(psych).toContain('snap.revision_id=a.question_revision_id')
    expect(psych).toContain("va.completed_at IS NOT NULL")
    expect(psych).toContain("s.status='completed'")
    expect(psych).toContain('CASE WHEN n<30 THEN NULL ELSE disc END')
  })
})
