export const PLATFORM_ADMIN_ENTRY_PERMISSIONS = [
  'admin.dashboard.view',
  'admin.full',
  'admin.homepage.view',
  'admin.homepage.edit',
  'admin.questions.view',
  'admin.questions.edit',
  'admin.questions.generate',
  'content.prepare',
  'content.review.stage1',
  'content.review.stage2',
  'content.publish',
  'content.appeals.manage',
  'content.corrections.apply',
  'content.enforcement.manage',
  'content.psychometrics.refresh',
  'admin.backgrounds.view',
  'admin.backgrounds.manage',
  'admin.badges.view',
  'admin.badges.manage',
  'admin.users.view',
  'admin.users.manage',
  'institution.pilots.manage',
  'institution.support.access',
  'admin.reports.view',
  'admin.reports.manage',
  'admin.logs.view',
  'admin.settings.view',
  'admin.settings.edit',
  'admin.roles.view',
  'admin.roles.manage',
] as const

export const INSTITUTION_PILOT_ENTRY_PERMISSION = 'institution.pilot.access'
