import {beforeEach,describe,expect,it,vi} from 'vitest'
const mocks=vi.hoisted(()=>({enabled:vi.fn(),context:vi.fn(),rpc:vi.fn(),analysis:vi.fn(),snapshot:vi.fn()}))
vi.mock('@/lib/institution-tracking/server-security',()=>({isInstitutionTrackingEnabled:mocks.enabled}))
vi.mock('@/lib/institution-pilot/route-context',()=>({requireInstitutionPilotRouteContext:mocks.context}))
vi.mock('@/lib/teacher-classroom/rate-limits',()=>({teacherClassroomWriteLimiter:{kind:'write'}}))
vi.mock('@/lib/institution-tracking/student-analysis',async(importOriginal)=>{const actual=await importOriginal<typeof import('@/lib/institution-tracking/student-analysis')>();return{...actual,buildInstitutionStudentLearningAnalysis:mocks.analysis}})
vi.mock('@/lib/institution-tracking/student-report',async(importOriginal)=>{const actual=await importOriginal<typeof import('@/lib/institution-tracking/student-report')>();return{...actual,buildInstitutionStudentReportSnapshot:mocks.snapshot}})
import {GET,POST} from '../route'
const USER_ID='11111111-1111-4111-8111-111111111111',CLASSROOM_ID='22222222-2222-4222-8222-222222222222',MEMBER_REF='a'.repeat(32),REQUEST_ID='33333333-3333-4333-8333-333333333333'
const directory={institution:{name:'Bilge Pilot Kursu',status:'pilot'},membership:{role:'teacher'},classrooms:[{id:CLASSROOM_ID,name:'TYT A Sınıfı',teacherAlias:'Öğretmen Bir',activeStudentCount:1,students:[{memberRef:MEMBER_REF,alias:'Öğrenci Bir',joinedAt:'2026-08-01T09:00:00.000Z'}]}]}
const snapshot={modelVersion:'institution-student-report-v1',generatedAt:'2026-08-14T10:00:00.000Z',periodStart:'2026-08-01T10:00:00.000Z',periodEnd:'2026-08-14T10:00:00.000Z',institutionName:'Bilge Pilot Kursu',classroomName:'TYT A Sınıfı',teacherAlias:'Öğretmen Bir',studentAlias:'Öğrenci Bir',scope:{game:'matematik',examRef:'TYT',taxonomyVersion:'ba-tyt-math-v1'},summary:{outcomeCount:0,assessedOutcomeCount:0,insufficientOutcomeCount:0,developingOutcomeCount:0,masteredOutcomeCount:0},outcomes:[]}
beforeEach(()=>{vi.clearAllMocks();mocks.enabled.mockReturnValue(true);mocks.context.mockResolvedValue({ok:true,userId:USER_ID,admin:{rpc:mocks.rpc}});mocks.analysis.mockReturnValue({scope:{}});mocks.snapshot.mockReturnValue(snapshot);mocks.rpc.mockImplementation(async(name)=>name==='get_institution_tracking_directory'?{data:directory,error:null}:name==='get_institution_student_learning_analysis'?{data:{},error:null}:name==='create_institution_student_report'?{data:{reportRef:'b'.repeat(32),snapshot,createdAt:'2026-08-14T10:01:00.000Z',replayed:false},error:null}:name==='get_institution_student_reports'?{data:{reports:[]},error:null}:{data:null,error:{code:'P0002'}})})
describe('institution student reports route',()=>{
  it('creates the snapshot server-side before the idempotent RPC',async()=>{const response=await POST(new Request('http://localhost',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({classroomId:CLASSROOM_ID,memberRef:MEMBER_REF,requestId:REQUEST_ID})}));expect(response.status).toBe(200);expect(mocks.snapshot).toHaveBeenCalledWith(expect.anything(),{institutionName:'Bilge Pilot Kursu',teacherAlias:'Öğretmen Bir'});expect(mocks.rpc).toHaveBeenCalledWith('create_institution_student_report',expect.objectContaining({p_snapshot:snapshot,p_request_id:REQUEST_ID}))})
  it('reads only the validated opaque member scope',async()=>{const response=await GET(new Request(`http://localhost/api/institution/tracking/reports?classroomId=${CLASSROOM_ID}&memberRef=${MEMBER_REF}`));expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('get_institution_student_reports',{p_user_id:USER_ID,p_classroom_id:CLASSROOM_ID,p_member_ref:MEMBER_REF})})
})
